version: '3.9'

x-app: &app
  env_file:
    - .env

services:
  app:
    <<: *app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/vite-react-app/ # exclude mount for "npm install"
    stdin_open: true
    tty: true