version: '3.9'

x-app: &app
  restart: always
  env_file:
    - .env

services:
  app:
    <<: *app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../:/app
      - /app/node_modules
    stdin_open: true
    tty: true