version: '3'

x-app: &app
  restart: always
  env_file:
    - .env

services:
  app:
    <<: *app
    build:
      context: .
    container_name: todo
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/todo_db

  db:
    <<: *app
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: